### ISSUE TITLE
Težava z ukazom push

### ISSUE THREAD

**Issue by Klarapenko** [Klarapenko/APPR-2019-20#4]
Pozdravljeni, 

Pričela sem z dokončanjem projekta, ki sem ga začela že v lanskem študijskem letu, vendar imam težavo pri ukazu push. Ko ga poskušam izvesti mi javi težavo in sicer:

![Screenshot 2021-08-18 at 17 46 06](https://user-images.githubusercontent.com/49915516/129930150-35d106b8-7eed-4ebb-85ab-90be44ae1245.png)

Prosim za pomoč

**Comment by timotejvesel** [comment]
Spodnje je delovalo pri meni (na Windowsih), mislim pa, da bi moralo tudi na drugih operacijskih sistemih.

Najprej sledi navodilom na tem [odgovoru](https://stackoverflow.com/a/68781050). Nato pa se v programu *Git Bash* postavi v mapo, kjer imaš shranjen projekt ter izvedi naslednji ukaz:
```
git remote set-url origin https://<token>@github.com/<username>/<repo>
```
kjer `token` nadomestiš s tokenom, ki si ga zgenerirala po zgornjih navodilih, `username` nadomestiš s svojim uporabniškim imenon na Githubu, `repo` pa z imenom repozitorija oziroma projekta.

**Comment by Klarapenko** [comment]
Pri zadnjem koraku mi javi naslednjo težavo: 

![Screenshot 2021-08-19 at 12 19 03](https://user-images.githubusercontent.com/49915516/130052443-16d4dfbf-20c5-418e-a588-415ed0c255b5.png)

Nevem če sem morda naredila napako že prej. In sicer pri 6. koraku na spodnji sliki

![Screenshot 2021-08-19 at 12 20 52](https://user-images.githubusercontent.com/49915516/130052665-2ab78244-144e-4f47-a6d4-205a811d1f93.png)

Sem zgeneriran token prilepila na obkroženo mesto na sliki 

![Screenshot 2021-08-19 at 12 22 02](https://user-images.githubusercontent.com/49915516/130052862-842f1cbd-4747-4c9f-ac4f-afcdb2a5b414.png)

**Comment by timotejvesel** [comment]
Malo površno sem napisal. `<token>` nadomestiš s tokenom, itd. Torej brez < in >.

**Comment by Klarapenko** [comment]
Hvala sem popravila, vendar sedaj ob ukazu push naletim na novo napako. Ko pritisnem push se mi pojavi okno za vpis gesla:
![Screenshot 2021-08-19 at 12 41 04](https://user-images.githubusercontent.com/49915516/130055354-b2f6ce68-10cd-4e18-87b5-82140bc365ab.png)
 
In ko vpišem geslo s katerim se vpisujem v github preko spleta, mi javi:

remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Klarapenko/APPR-2019-20/'

**Comment by timotejvesel** [comment]
Kaj pa, če namesto gesla od githuba vpišeš `token`?

**Comment by Klarapenko** [comment]
Sem poskusila pa ne deluje.

**Comment by jaanos** [comment]
Mislim, da bo potrebno v URL-ju pred `@` namesto tokena podati uporabniško ime (torej `Klarapenko`), potem pa namesto gesla uporabiš token.

Mimogrede, token služi za avtentikacijo, zato z njim ravnaj kot z geslom. Glede na to, da si trenutnega objavila v slikah, svetujem, da ga prekličeš (_revoke_) ter generiraš in uporabiš novega.

**Comment by jaanos** [comment]
Še to: v Keychain access pazi na velikost črk pri svojem uporabniškem imenu (naj bo torej `Klarapenko`, brez velike začetnice priimka). Če je to pravilno konfigurirano, ti ne bo treba tokena vsakič vpisovati.

**Comment by Klarapenko** [comment]
nevem če prav razumem, uporabim sledeči zapis: 

git remote set-url origin https://Klarapenko@github.com/Klarapenko/APPR-2019-20

ali na mestu kjer je zgoraj drugič zapisano uporabniško ime zapišem token?

Hvala, sem v keychain access popravila veliko začetnico.

**Comment by jaanos** [comment]
Tako kot si napisala, ja. Če še vedno ne bo šlo, pa poskusi odstraniti `Klarapenko@` - z nastavitvami v Keychain access bi moralo tudi tako delovati.

**Comment by Klarapenko** [comment]
Sem poskusila obe verziji, pa mi v obeh primerih javi:
![Uploading Screenshot 2021-08-19 at 13.20.44.png…]()

**Comment by Klarapenko** [comment]
Sem poskusila obe verziji, pa mi v obeh primerih javi:
![Screenshot 2021-08-19 at 13 20 44](https://user-images.githubusercontent.com/49915516/130060401-6a573480-e0a5-47bc-840f-9711c9bf9f91.png)

**Comment by katarinabrilej** [comment]
Bom še jaz probala ugotoviti kako rešiti težavo. Sem probala na enem svojem projektu iz tega semestra nekaj spremeniti in klikniti push in naletim na isto težavo (in imam Mac-a). Sporočim, ko jo uspem razrešiti pri sebi, upam da bo enako delovalo tudi pri tebi.

**Comment by katarinabrilej** [comment]
Sem uspela razrešiti. Potrebno je samo slediti navodilom na https://stackoverflow.com/questions/68775869/support-for-password-authentication-was-removed-please-use-a-personal-access-to.
Potem ko te vpraša za geslo, ko klikneš push, je to geslo od računalnika.

Upam, da bo delovalo.

**Comment by Klarapenko** [comment]
Sedaj mi deluje. Vidim, da je bil problem le v tem, da mi ni bilo potrebno v git bash vpisati ukaza git remote set-url...

Vsem najlepša hvala za pomoč.
